include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/linux.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/android.yml
      - /gitlab-templates/android-qt6.yml
      - /gitlab-templates/freebsd.yml
      - /gitlab-templates/freebsd-qt6.yml
      #- /gitlab-templates/flatpak.yml
  
appstream:
  image:
    name: archlinux:latest
    entrypoint: [""]
  stage: build
  script:
    - pacman -Sy appstream --noconfirm
    - appstreamcli validate org.kde.kweather.appdata.xml
