include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/android-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml
  #    - /gitlab-templates/flatpak.yml
