# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "KWeather"
SPDX-PackageDownloadLocation = "https://invent.kde.org/plasma-mobile/kweather"

[[annotations]]
path = "android/ic_launcher-playstore.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Gabriel Souza Franco"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["android/res/drawable/kweather.png", "android/res/mipmap-hdpi/ic_launcher.png", "android/res/mipmap-xhdpi/ic_launcher.png", "android/res/mipmap-xxhdpi/ic_launcher.png", "android/res/mipmap-xxxhdpi/ic_launcher.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Devin Lin <espidev@gmail.com>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "android/res/mipmap-mdpi/ic_launcher.png"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2020 Gabriel Souza Franco", "2020 Devin Lin <espidev@gmail.com>"]
SPDX-License-Identifier = "CC-BY-4.0"
